### ISSUE TITLE
Follow GNU conventions for --version

### ISSUE THREAD

**Issue by bstarynk** [kingletbv/carburetta#1]
Hello,

It would be nice to have carburetta (from github) follow the GNU conventions. So accepting `--help` and `--version` as program first arguments.

The below patch (on Linux/x86-64 Debian sid) is a suggestion:

     diff --git a/Makefile b/Makefile
     index 2f56c73..8b5b44f 100644
     --- a/Makefile
     +++ b/Makefile
     @@ -1,5 +1,10 @@
     -CC=gcc
     +CC=gcc-13
     +CXX=g++-13
      
     +GIT_ID := $(shell git log --format=oneline -q -1 | cut -c1-10)
     +
     +CFLAGS+= -O -g
     +CXXFLAGS+= -O -g
      OUT = build/linux
      SRC = src
      INTERMEDIATE = build/linux/objs
     @@ -14,10 +19,10 @@ all: $(OUT)/carburetta $(OUT)/calc $(OUT)/template_scan $(OUT)/inireader $(OUT)/
      
      $(INTERMEDIATE)/%.o: $(SRC)/%.c
      	@mkdir -p $(@D)
     -	$(CC) -c -o $@ $<
     +	$(CC) $(CFLAGS) -DCARBURETTA_GIT_ID=\"$(GIT_ID)\" -c -o $@ $<
      
      $(OUT)/carburetta: $(OBJECTS)
     -	$(CC) -o $(OUT)/carburetta $(OBJECTS)
     +	$(CC) $(CFLAGS) -o $(OUT)/carburetta $(OBJECTS)
      
      $(INTERMEDIATE)/calc/calc.c: $(OUT)/carburetta examples/calc/calc.cbrt
      	mkdir -p $(@D)
     @@ -32,13 +37,13 @@ $(INTERMEDIATE)/template_scan/template_scan.c: $(OUT)/carburetta examples/templa
      	$(OUT)/carburetta examples/template_scan/template_scan.cbrt --c $(INTERMEDIATE)/template_scan/template_scan.c
      
      $(OUT)/calc: $(INTERMEDIATE)/calc/calc.c
     -	$(CC) -o $(OUT)/calc $(INTERMEDIATE)/calc/calc.c
     +	$(CC) $(CFLAGS) -o $(OUT)/calc $(INTERMEDIATE)/calc/calc.c
      
      $(OUT)/inireader: $(INTERMEDIATE)/inireader/iniparser.c examples/inireader/main.c
     -	$(CC) -o $(OUT)/inireader -I$(INTERMEDIATE)/inireader -Iexamples/inireader $(INTERMEDIATE)/inireader/iniparser.c examples/inireader/main.c
     +	$(CC) $(CFLAGS) -o $(OUT)/inireader -I$(INTERMEDIATE)/inireader -Iexamples/inireader $(INTERMEDIATE)/inireader/iniparser.c examples/inireader/main.c
      
      $(OUT)/template_scan: $(INTERMEDIATE)/template_scan/template_scan.c
     -	$(CC) -o $(OUT)/template_scan $(INTERMEDIATE)/template_scan/template_scan.c
     +	$(CC) $(CFLAGS) -o $(OUT)/template_scan $(INTERMEDIATE)/template_scan/template_scan.c
      
      $(INTERMEDIATE)/tester/%.c: tester/%.cbrt
      	mkdir -p $(@D)
     @@ -49,7 +54,7 @@ $(INTERMEDIATE)/tester/t3.c: tester/t3.cbrt
      	$(OUT)/carburetta $< --c $@ --h
      
      $(OUT)/tester: $(TESTS_C) tester/tester.c
     -	$(CC) -o $@ $^
     +	$(CC) $(CFLAGS) -o $@ $^
      
      .PHONY: clean
      clean:
     diff --git a/src/carburetta.c b/src/carburetta.c
     index 885dafe..f0bfc77 100644
     --- a/src/carburetta.c
     +++ b/src/carburetta.c
     @@ -138,6 +138,9 @@
      #include "indented_printer.h"
      #endif
      
     +#ifndef CARBURETTA_VERSION
     +#define CARBURETTA_VERSION "0.8.9"
     +#endif
      
      /* Following globals control the output file. If we fail execution (eg. user error in the input or an
       * unforeseen problem internally) then we wish to retain whatever output was already there.
     @@ -190,7 +193,7 @@ void print_dbg_char(FILE *fp, int c) {
      
      void print_usage(void) {
        fprintf(stderr, "Carburetta parser generator (C) 2020-2023 Kinglet B.V.\n"
     -                  "version 0.8.9\n"
     +                  CARBURETTA_VERSION "\n"
                        "https://carburetta.com/\n"
                        "\n"
                        "carburetta <inputfile.cbrt> [ --c [ <c_filename> [--h [h_filename] ] ] ]\n"
     @@ -218,6 +221,24 @@ void print_usage(void) {
      int main(int argc, char **argv) {
        int r;
      
     +  if (argc == 2 && !strcmp(argv[1], "--help"))
     +    {
     +      print_usage();
     +      exit (EXIT_SUCCESS);
     +    }
     +  else if (argc == 2 && !strcmp(argv[1], "--version")) {
     +    printf("%s version %s built %s git %s\n", argv[0], CARBURETTA_VERSION,
     +	   __DATE__"@"__TIME__,
     +#ifdef CARBURETTA_GIT_ID
     +	   CARBURETTA_GIT_ID
     +#else
     +	   "???"
     +#endif
     +	   );
     +    printf("See https://carburetta.com/\n");
     +    exit (EXIT_SUCCESS);
     +  };
     +  
        r = ldl_init();
        if (r) {
          re_error_nowhere("Failed to initialize ldl");

Regards from near Paris.

Basile Starynkevitch <basile.starynkevitch@cea.fr> and <basile@starynkevitch.net>

NB: we might use carburetta in http://refpersys.org/

**Comment by martijnboekhorst** [comment]
Please note I cannot take patches due to keeping the copyright single source, but bugs and suggestions are very welcome.

--version and --help have been implemented as per gnu style guidelines. Note that I did not take the git commit id suggestion so as not to create unnecessary coupling between build system, platform, and source.

https://github.com/kingletbv/carburetta/commit/f9b9bebd2eea8cbf2c8a03129e9a31f4183afadf
